In [9]:
import os
import json
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv

from options import OptionSurface, Deribit, OKX, Bybit
from portfolio_management import Portfolio
from api_client import TradingDeskAPI
from scanner import MarketScanner

In [10]:
# Initialize all classes and parameters

load_dotenv(r"D:/OneDrive/Trading/Prediction Markets/Moreton Capital/.env")
BASE_URL = os.getenv("BASE_URL")
USER_EMAIL = os.getenv("USER_EMAIL")
USER_PASSWORD = os.getenv("USER_PASSWORD")
JWT_TOKEN = os.getenv("JWT")
DATA_DIR = os.getenv("DATA_DIR")
FRACTION = float(os.getenv("FRACTION"))
MAX_POSITION = float(os.getenv("MAX_POSITION"))
ENTRY_EV_THRESHOLD = float(os.getenv("ENTRY_EV_THRESHOLD")) # require 1% edge, default = 0
EXIT_EV_THRESHOLD = float(os.getenv("EXIT_EV_THRESHOLD"))
print(BASE_URL)

with open(f"{DATA_DIR}/crypto_tag_ids.json", "r") as f:
    crypto_tag_ids = set(json.load(f))

s = OptionSurface()
portfolio = Portfolio()
api = TradingDeskAPI(base_url=BASE_URL, email=USER_EMAIL, password=USER_PASSWORD, token=JWT_TOKEN)
scanner = MarketScanner(api=api)

target_expiry_str = "25DEC26"
target_expiry = datetime.strptime(target_expiry_str, "%d%b%y").strftime("%Y%m%d")

currencies = ["BTC", "ETH"]
# currencies = ["BTC", "ETH", "HYPE", "SOL", "ZEC"]

https://alphasignal-dev.moretoncp.com

In [11]:
# 1. Get all dfs
orders_df = pd.read_parquet(f"{DATA_DIR}/orders.parquet")
fills_df = pd.read_parquet(f"{DATA_DIR}/fills.parquet")
positions_df = pd.read_parquet(f"{DATA_DIR}/positions.parquet")
realized_pnl_df = pd.read_parquet(f"{DATA_DIR}/realized_pnl.parquet") # will be overwritten
equity_df = pd.read_parquet(f"{DATA_DIR}/equity.parquet")

# fills_df = fills_df.iloc[0:0]

In [ ]:
# BACKTEST

# # 1. Get all dfs
# orders_df_backtest = pd.read_parquet(f"{DATA_DIR}/orders_backtest.parquet")
# fills_df_backtest = pd.read_parquet(f"{DATA_DIR}/fills_backtest.parquet")
# positions_df_backtest = pd.read_parquet(f"{DATA_DIR}/positions_backtest.parquet")
# realized_pnl_df_backtest = pd.read_parquet(f"{DATA_DIR}/realized_pnl_backtest.parquet") # will be overwritten
# equity_df_backtest = pd.read_parquet(f"{DATA_DIR}/equity_backtest.parquet")

# fills_df_backtest = portfolio.sync_fills_test(api=api, fills_df=fills_df)
# positions_df_backtest, realized_pnl_df_backtest = portfolio.reconstruct_positions_fifo(fills_df=fills_df_backtest)
# positions_df_backtest = portfolio.mark_positions_to_market(api=api, positions_df=positions_df_backtest)
# equity_df_backtest = portfolio.calculate_equity(api=api, positions_df=positions_df_backtest, 
#                                 realized_pnl_df=realized_pnl_df_backtest, equity_df=equity_df_backtest)

In [12]:
# 2. Get newly executed trades
fills_df = portfolio.sync_fills(api=api, fills_df=fills_df)
fills_df

,order_id,condition_id,token_id,outcome,side,price,shares,fee_rate,fee_rate_bps,timestamp,fill_id
0,0x8039083a81a0749075a21658567ad6e0e449ea2ac99e...,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,No,BUY,0.981,4.87,0.07,0.0,2026-08-14 08:25:11+00:00,4c3c68e2-7b89-463c-ae03-48b92808eeef
1,0xf7ff5b16da1bb114dc0b34d7e83324beb8b85502f029...,0xb75b8c777c5fd934d7fa43d4b3a3f630981b68a362a0...,4479131210875376621873271572183009281689857070...,No,BUY,0.969,4.91,0.07,0.0,2026-08-19 08:01:06+00:00,cd0ebe33-7e52-44c6-a022-466914d90934
2,0x387e06d4de5bb3110d135297db63ce667c4a3ac0de7d...,0xa3143f9c21ecc7a9b036b4e435f48264ff72019a9e3e...,4251240413067872674686064123803499349976238079...,No,BUY,0.960,4.95,0.07,0.0,2026-08-19 08:00:45+00:00,ff80c017-a13d-43ee-85c0-35a2c289c1b6

In [13]:
# 3. Reconstruct portfolio
# 4. Calculate realized P&L
positions_df, realized_pnl_df = portfolio.reconstruct_positions_fifo(fills_df=fills_df) # new realized_df to overwrite old
realized_pnl_df

,condition_id,token_id,outcome,realized_shares,realized_pnl,realized_fees
0,0xa3143f9c21ecc7a9b036b4e435f48264ff72019a9e3e...,4251240413067872674686064123803499349976238079...,No,0.0,0.0,0.0
1,0xb75b8c777c5fd934d7fa43d4b3a3f630981b68a362a0...,4479131210875376621873271572183009281689857070...,No,0.0,0.0,0.0
2,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,No,0.0,0.0,0.0

In [14]:
# 5. Sync positions with api
portfolio.reconcile_positions(api=api, positions_df=positions_df)

POSITIONS SYNCED
POSITIONS SYNCED
POSITIONS SYNCED

In [15]:
# 6. Get latest order state
orders_df = portfolio.sync_orders(api=api, orders_df=orders_df)
orders_df

,order_id,condition_id,token_id,outcome,side,price,requested_size,order_type,status,created_at,cancelled_at
0,0x8039083a81a0749075a21658567ad6e0e449ea2ac99e...,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,NO,buy,0.981,4.877934,GTC,OPEN,2026-08-14 09:28:01.978131+00:00,NaT
1,0x387e06d4de5bb3110d135297db63ce667c4a3ac0de7d...,0xa3143f9c21ecc7a9b036b4e435f48264ff72019a9e3e...,4251240413067872674686064123803499349976238079...,NO,buy,0.960,4.959176,GTC,OPEN,2026-08-19 08:00:40.748876+00:00,NaT
2,0xf7ff5b16da1bb114dc0b34d7e83324beb8b85502f029...,0xb75b8c777c5fd934d7fa43d4b3a3f630981b68a362a0...,4479131210875376621873271572183009281689857070...,NO,buy,0.969,4.913116,GTC,OPEN,2026-08-19 08:01:02.498064+00:00,NaT

In [17]:
# 7. Mark positions to market
positions_df = portfolio.mark_positions_to_market(api=api, positions_df=positions_df)
positions_df

,condition_id,token_id,outcome,shares,cost_basis,avg_entry_price,realized_pnl,realized_shares,realized_fees,current_price,market_value,unrealized_pnl,unrealized_return
0,0xa3143f9c21ecc7a9b036b4e435f48264ff72019a9e3e...,4251240413067872674686064123803499349976238079...,No,4.95,4.765306,0.962688,0.0,0.0,0.0,0.950,4.70250,-0.062806,-0.013180
1,0xb75b8c777c5fd934d7fa43d4b3a3f630981b68a362a0...,4479131210875376621873271572183009281689857070...,No,4.91,4.768114,0.971103,0.0,0.0,0.0,0.968,4.75288,-0.015234,-0.003195
2,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,No,4.87,4.783824,0.982305,0.0,0.0,0.0,0.982,4.78234,-0.001484,-0.000310

In [18]:
# 8. Calculate equity
equity_df = portfolio.calculate_equity(api=api, positions_df=positions_df, 
                                realized_pnl_df=realized_pnl_df, equity_df=equity_df)
equity_df

Equity:  99.92
Return:  0.0000%
Sharpe: N/A
Sortino: N/A

,timestamp,cash,market_value,equity,realized_pnl,unrealized_pnl,daily_return,period_return,sharpe,sortino
0,2026-08-14 07:47:24.047885+00:00,100.00000,0.00000,100.00000,0.0,0.000000,NaN,NaN,NaN,NaN
1,2026-08-15 14:14:05.272655+00:00,95.21618,4.79695,100.01313,0.0,0.019480,NaN,0.000131,NaN,NaN
2,2026-08-17 02:58:57.343900+00:00,95.21618,4.77747,99.99365,0.0,0.000000,NaN,-0.000195,NaN,NaN
3,2026-08-19 07:56:33.538278+00:00,95.21618,4.78234,99.99852,0.0,0.004870,NaN,0.000049,NaN,NaN
4,2026-08-19 08:05:37.263592+00:00,85.68277,14.23772,99.92049,0.0,-0.049540,NaN,-0.000780,NaN,NaN
5,2026-08-19 11:33:46.319333+00:00,85.68277,14.23772,99.92049,0.0,-0.079524,NaN,0.000000,NaN,NaN

In [12]:
# 9. Get current markets
all_markets_df = api.get_all_markets(DATA_DIR=DATA_DIR, count_limit=10, liquidity_num_min=10000, volume_num_min=5000)
all_markets_df.head()

Fetched 100 markets | Total: 100
Fetched 100 markets | Total: 200
Fetched 100 markets | Total: 300
Fetched 100 markets | Total: 400
Fetched 100 markets | Total: 500
Fetched 100 markets | Total: 600
Fetched 100 markets | Total: 700
Fetched 100 markets | Total: 800
Fetched 100 markets | Total: 900
Fetched 100 markets | Total: 1,000

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,...,version,negRiskMarketID,seriesColor,showGmpSeries,showGmpOutcome,umaResolutionStatus,oneHourPriceChange,eventStartTime,gameStartTime,groupItemRange
0,559651,Xi Jinping out before 2027?,0xa467b14d51f01b957109d9cbb1d6c124fab2a089d52e...,xi-jinping-out-before-2027,,2026-12-31T00:00:00Z,265073.20748,2025-07-03T20:37:00.228Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,v1,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN
1,559652,Will Gavin Newsom win the 2028 Democratic pres...,0x0f49db97f71c68b1e42a6d16e3de93d85dbf7d4148e3...,will-gavin-newsom-win-the-2028-democratic-pres...,,2028-11-07T00:00:00Z,301250.22354,2025-07-11T18:35:56.805Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,v1,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,,False,False,NaN,NaN,NaN,NaN,NaN
2,559653,Will Alexandria Ocasio-Cortez win the 2028 Dem...,0xe6bcc2f1dd025ce5e1833190f7c60a71171c94f805df...,will-alexandria-ocasio-cortez-win-the-2028-dem...,,2028-11-07T00:00:00Z,360252.86913,2025-07-11T18:35:59.075Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,v1,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,,False,False,NaN,NaN,NaN,NaN,NaN
3,559654,Will Pete Buttigieg win the 2028 Democratic pr...,0x4c325469d9b516ef4e6b8f73a81a12607dec075e3c2f...,will-pete-buttigieg-win-the-2028-democratic-pr...,,2028-11-07T00:00:00Z,528145.823,2025-07-11T18:35:58.818Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,v1,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,,False,False,NaN,NaN,NaN,NaN,NaN
4,559655,Will Josh Shapiro win the 2028 Democratic pres...,0xd65891729ce093cc12236856837eba1a0872fc7998fd...,will-josh-shapiro-win-the-2028-democratic-pres...,,2028-11-07T00:00:00Z,483420.49813,2025-07-11T18:36:01.098Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,v1,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,,False,False,NaN,NaN,NaN,NaN,NaN

In [13]:
# 10. Initialize variance surface
deribit = Deribit(currencies=currencies, target_expiry=target_expiry)
okx = OKX(currencies=currencies, target_expiry=target_expiry)
bybit = Bybit(currencies=currencies, target_expiry=target_expiry)

s.initialize(currencies=currencies, exchanges=[deribit, okx, bybit])

spot: 64383.0 volume24h: 0.6203
spot: 1919.6 volume24h: 25.5051
spot: 64389.2 volume24h: 3978.75931279
spot: 1918.35 volume24h: 52864.473492
spot: 64382.6 volume24h: 5758.963178
spot: 1918.28 volume24h: 54187.0553

In [14]:
# 11. Scan markets
markets_df, opportunities_df = scanner.scan_market(markets_df=all_markets_df, s=s, crypto_tag_ids=crypto_tag_ids)
opportunities_df.head()

question: Will Bitcoin hit $150k by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 150000.0
iv: 0.5128221544606524
buy_yes_ev: -0.009752223374581929
sell_yes_ev: 0.00702413337458193
buy_no_ev: 0.0070241333745819
sell_no_ev: -0.009752223374581974
buy_yes_kelly: -0.004944835856648765
sell_yes_kelly: 0.314417326222459
buy_no_kelly: 0.3144173262224585
sell_no_kelly: -0.004944835856648787

question: Will Bitcoin reach $200,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 200000.0
iv: 0.5866136351633732
buy_yes_ev: -0.018454256582258875
sell_yes_ev: 0.015047166582258874
buy_no_ev: 0.01504716658225893
sell_no_ev: -0.01845425658225888
buy_yes_kelly: -0.009408115214099946
sell_yes_kelly: 0.47526683384445056
buy_no_kelly: 0.4752668338444506
sell_no_kelly: -0.00940811521409995

question: Will Bitcoin reach $190,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 190000.0
iv: 0.5771037810477258
buy_yes_ev: -0.021329226681359992
sell_yes_ev: 0.01751809668135999
buy_no_ev: 0.01751809668135997
sell_no_ev: -0.021329226681359965
buy_yes_kelly: -0.01090941103307459
sell_yes_kelly: 0.4702087363474337
buy_no_kelly: 0.4702087363474337
sell_no_kelly: -0.010909411033074577

question: Will Bitcoin reach $180,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 180000.0
iv: 0.5744457703189334
buy_yes_ev: -0.02061818372568107
sell_yes_ev: 0.01587432372568107
buy_no_ev: 0.01587432372568111
sell_no_ev: -0.02061818372568104
buy_yes_kelly: -0.010545728843300095
sell_yes_kelly: 0.44854708986302755
buy_no_kelly: 0.44854708986302766
sell_no_kelly: -0.01054572884330008

question: Will Bitcoin reach $170,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 170000.0
iv: 0.5562258092098065
buy_yes_ev: -0.021135413501009667
sell_yes_ev: 0.017190163501009673
buy_no_ev: 0.01719016350100973
sell_no_ev: -0.021135413501009746
buy_yes_kelly: -0.010822092147167202
sell_yes_kelly: 0.4394018134420829
buy_no_kelly: 0.439401813442083
sell_no_kelly: -0.010822092147167246

question: Will Bitcoin reach $160,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 160000.0
iv: 0.5243659777827662
buy_yes_ev: -0.025200007685429057
sell_yes_ev: 0.02072107768542906
buy_no_ev: 0.02072107768542906
sell_no_ev: -0.025200007685429054
buy_yes_kelly: -0.012959935998007677
sell_yes_kelly: 0.4447776267331164
buy_no_kelly: 0.4447776267331164
sell_no_kelly: -0.012959935998007675

question: Will Bitcoin reach $150,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 150000.0
iv: 0.5128221544606524
buy_yes_ev: -0.022560303374581932
sell_yes_ev: 0.01821437337458193
buy_no_ev: 0.01821437337458192
sell_no_ev: -0.022560303374581973
buy_yes_kelly: -0.01158966826540391
sell_yes_kelly: 0.40729232351285516
buy_no_kelly: 0.4072923235128551
sell_no_kelly: -0.01158966826540393

question: Will Bitcoin reach $140,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 140000.0
iv: 0.4858453843305042
buy_yes_ev: -0.026523182030252036
sell_yes_ev: 0.021515052030252044
buy_no_ev: 0.021515052030252023
sell_no_ev: -0.026523182030252022
buy_yes_kelly: -0.013700514394791969
sell_yes_kelly: 0.3980013228494577
buy_no_kelly: 0.39800132284945755
sell_no_kelly: -0.013700514394791962

question: Will Bitcoin reach $130,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 130000.0
iv: 0.4685571266164444
buy_yes_ev: -0.027117526047629372
sell_yes_ev: 0.02158467604762937
buy_no_ev: 0.021584676047629377
sell_no_ev: -0.027117526047629407
buy_yes_kelly: -0.014069471910242326
sell_yes_kelly: 0.3507851961002269
buy_no_kelly: 0.35078519610022696
sell_no_kelly: -0.014069471910242343

question: Will Bitcoin reach $120,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 120000.0
iv: 0.4434081354587941
buy_yes_ev: -0.03860000600847664
sell_yes_ev: 0.02258700600847664
buy_no_ev: 0.022587006008476653
sell_no_ev: -0.038600006008476705
buy_yes_kelly: -0.020387147652825226
sell_yes_kelly: 0.3026775033297148
buy_no_kelly: 0.30267750332971494
sell_no_kelly: -0.02038714765282526

question: Will Bitcoin reach $110,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 110000.0
iv: 0.42427616282422104
buy_yes_ev: -0.03592642714594583
sell_yes_ev: 0.018653427145945825
buy_no_ev: 0.018653427145945846
sell_no_ev: -0.03592642714594583
buy_yes_kelly: -0.019190401359083592
sell_yes_kelly: 0.1998224654091679
buy_no_kelly: 0.19982246540916804
sell_no_kelly: -0.019190401359083592

question: Will Bitcoin reach $100,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 100000.0
iv: 0.4070923208988932
buy_yes_ev: -0.026316308197059754
sell_yes_ev: 0.00660730819705975
buy_no_ev: 0.006607308197059666
sell_no_ev: -0.026316308197059754
buy_yes_kelly: -0.014382885570641109
sell_yes_kelly: 0.050481397529604004
buy_no_kelly: 0.050481397529603435
sell_no_kelly: -0.014382885570641109

question: Will Bitcoin dip to $55,000 by December 31, 2026?
event type: touch
direction: down
currency: BTC
required strike: 55000.0
iv: 0.4354589815209722
buy_yes_ev: 0.03544039396713994
sell_yes_ev: -0.08026539396713991
buy_no_ev: -0.08026539396713986
sell_no_ev: 0.03544039396713994
buy_yes_kelly: 0.04003550961919236
sell_yes_kelly: -0.07829807649707442
buy_no_kelly: -0.07829807649707435
sell_no_kelly: 0.04003550961919236

question: Will Bitcoin dip to $45,000 by December 31, 2026?
event type: touch
direction: down
currency: BTC
required strike: 45000.0
iv: 0.5074767151453821
buy_yes_ev: 0.056843339678114724
sell_yes_ev: -0.09046833967811474
buy_no_ev: -0.09046833967811474
sell_no_ev: 0.056843339678114724
buy_yes_kelly: 0.03700796085232759
sell_yes_kelly: -0.2280097478113857
buy_no_kelly: -0.2280097478113857
sell_no_kelly: 0.03700796085232759

question: Will Bitcoin dip to $35,000 by December 31, 2026?
event type: touch
direction: down
currency: BTC
required strike: 35000.0
iv: 0.6223120897988099
buy_yes_ev: 0.03483702622533516
sell_yes_ev: -0.05687002622533521
buy_no_ev: -0.05687002622533523
sell_no_ev: 0.034837026225335244
buy_yes_kelly: 0.01949033580918382
sell_yes_kelly: -0.3374394853580596
buy_no_kelly: -0.33743948535805973
sell_no_kelly: 0.019490335809183867

question: Will Bitcoin dip to $25,000 by December 31, 2026?
event type: touch
direction: down
currency: BTC
required strike: 25000.0
iv: 0.7717646400380254
buy_yes_ev: 0.03293860861531728
sell_yes_ev: -0.04007805861531728
buy_no_ev: -0.0400780586153173
sell_no_ev: 0.03293860861531725
buy_yes_kelly: 0.017051940466126188
sell_yes_kelly: -0.7413935287586437
buy_no_kelly: -0.7413935287586444
sell_no_kelly: 0.017051940466126174

question: Will Ethereum reach $10,000 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 10000.0
iv: 0.7803850194042704
buy_yes_ev: -0.011561570225842983
sell_yes_ev: 0.008175710225842984
buy_no_ev: 0.008175710225843041
sell_no_ev: -0.011561570225843004
buy_yes_kelly: -0.005849585184557217
sell_yes_kelly: 0.48806305799076277
buy_no_kelly: 0.4880630579907629
sell_no_kelly: -0.005849585184557227

question: Will Ethereum reach $8,000 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 8000.0
iv: 0.7513471359211358
buy_yes_ev: -0.020570090890031523
sell_yes_ev: 0.015960770890031523
buy_no_ev: 0.015960770890031555
sell_no_ev: -0.02057009089003158
buy_yes_kelly: -0.010509657852642434
sell_yes_kelly: 0.4760805220296374
buy_no_kelly: 0.47608052202963747
sell_no_kelly: -0.010509657852642464

question: Will Ethereum reach $7,500 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 7500.0
iv: 0.737310847666796
buy_yes_ev: -0.024535440161321174
sell_yes_ev: 0.020322790161321172
buy_no_ev: 0.020322790161321186
sell_no_ev: -0.024535440161321226
buy_yes_kelly: -0.012590537431430487
sell_yes_kelly: 0.4742325502256069
buy_no_kelly: 0.47423255022560695
sell_no_kelly: -0.012590537431430513

question: Will Ethereum reach $7,000 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 7000.0
iv: 0.6892923539007298
buy_yes_ev: -0.025729300590991943
sell_yes_ev: 0.02138337059099194
buy_no_ev: 0.02138337059099193
sell_no_ev: -0.025729300590991985
buy_yes_kelly: -0.013217644000586639
sell_yes_kelly: 0.4781543956211705
buy_no_kelly: 0.47815439562117046
sell_no_kelly: -0.01321764400058666

question: Will Ethereum reach $6,500 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 6500.0
iv: 0.6951534634952897
buy_yes_ev: -0.025800403424053184
sell_yes_ev: 0.02132147342405319
buy_no_ev: 0.02132147342405319
sell_no_ev: -0.02580040342405318
buy_yes_kelly: -0.013268709330269171
sell_yes_kelly: 0.4576651124025369
buy_no_kelly: 0.4576651124025369
sell_no_kelly: -0.01326870933026917

question: Will Ethereum reach $6,000 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 6000.0
iv: 0.6709471817156029
buy_yes_ev: -0.030351282916388354
sell_yes_ev: 0.020542302916388363
buy_no_ev: 0.020542302916388363
sell_no_ev: -0.030351282916388438
buy_yes_kelly: -0.015695195269497635
sell_yes_kelly: 0.44094022895386875
buy_no_kelly: 0.44094022895386875
sell_no_kelly: -0.01569519526949768

question: Will Ethereum reach $5,500 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 5500.0
iv: 0.6475414155688566
buy_yes_ev: -0.0300101668819098
sell_yes_ev: 0.0247391168819098
buy_no_ev: 0.024739116881909776
sell_no_ev: -0.030010166881909828
buy_yes_kelly: -0.015535919717351682
sell_yes_kelly: 0.4280528382423288
buy_no_kelly: 0.42805283824232876
sell_no_kelly: -0.015535919717351696

question: Will Ethereum reach $5,000 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 5000.0
iv: 0.6273110718827407
buy_yes_ev: -0.034563704264836126
sell_yes_ev: 0.020903174264836125
buy_no_ev: 0.020903174264836198
sell_no_ev: -0.0345637042648362
buy_yes_kelly: -0.0180324253290756
sell_yes_kelly: 0.3737648725965763
buy_no_kelly: 0.37376487259657665
sell_no_kelly: -0.018032425329075643

question: Will Ethereum reach $4,500 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 4500.0
iv: 0.6000580735000766
buy_yes_ev: -0.041210044947219984
sell_yes_ev: 0.025197044947219978
buy_no_ev: 0.02519704494721999
sell_no_ev: -0.04121004494722005
buy_yes_kelly: -0.021765677210880175
sell_yes_kelly: 0.3376533681820859
buy_no_kelly: 0.33765336818208597
sell_no_kelly: -0.021765677210880213

question: Will Ethereum reach $4,000 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 4000.0
iv: 0.5742789865703617
buy_yes_ev: -0.0404261772371048
sell_yes_ev: 0.0231531772371048
buy_no_ev: 0.023153177237104822
sell_no_ev: -0.0404261772371048
buy_yes_kelly: -0.021593980482443712
sell_yes_kelly: 0.2480254658500782
buy_no_kelly: 0.2480254658500783
sell_no_kelly: -0.021593980482443712

question: Will Ethereum reach $3,500 by December 31, 2026?
event type: touch
direction: up
currency: ETH
required strike: 3500.0
iv: 0.5529433491803798
buy_yes_ev: -0.03226800485661256
sell_yes_ev: 0.012559004856612557
buy_no_ev: 0.012559004856612467
sell_no_ev: -0.03226800485661256
buy_yes_kelly: -0.017635719188658968
sell_yes_kelly: 0.09595376783317205
buy_no_kelly: 0.09595376783317149
sell_no_kelly: -0.017635719188658968

question: Will Ethereum dip to $1,500 by December 31, 2026?
event type: touch
direction: down
currency: ETH
required strike: 1500.0
iv: 0.5570158755081392
buy_yes_ev: 0.10416213933653987
sell_yes_ev: -0.13880378933653983
buy_no_ev: -0.13880378933653983
sell_no_ev: 0.10416213933653987
buy_yes_kelly: 0.08961382271754244
sell_yes_kelly: -0.18064656708732285
buy_no_kelly: -0.18064656708732285
sell_no_kelly: 0.08961382271754244

question: Will Ethereum dip to $1,000 by December 31, 2026?
event type: touch
direction: down
currency: ETH
required strike: 1000.0
iv: 0.6782981341942661
buy_yes_ev: 0.025914045485223997
sell_yes_ev: -0.05960604548522397
buy_no_ev: -0.05960604548522397
sell_no_ev: 0.025914045485224038
buy_yes_kelly: 0.014848617870351861
sell_yes_kelly: -0.3180685458122944
buy_no_kelly: -0.3180685458122944
sell_no_kelly: 0.014848617870351886

question: Will Ethereum dip to $800 by December 31, 2026?
event type: touch
direction: down
currency: ETH
required strike: 800.0
iv: 0.7572718672143801
buy_yes_ev: 0.010774216371799095
sell_yes_ev: -0.02927921637179911
buy_no_ev: -0.029279216371798998
sell_no_ev: 0.010774216371799122
buy_yes_kelly: 0.005821112900415852
sell_yes_kelly: -0.2611790513433875
buy_no_kelly: -0.261179051343386
sell_no_kelly: 0.005821112900415867

question: Will Bitcoin reach $250,000 by December 31, 2026?
event type: touch
direction: up
currency: BTC
required strike: 250000.0
iv: 0.6124332879262753
buy_yes_ev: -0.018045000171000067
sell_yes_ev: 0.014773150171000064
buy_no_ev: 0.014773150171000072
sell_no_ev: -0.01804500017100004
buy_yes_kelly: -0.009189470653699502
sell_yes_kelly: 0.4958125084239969
buy_no_kelly: 0.4958125084239969
sell_no_kelly: -0.009189470653699489

question: Will Bitcoin dip to $15,000 by December 31, 2026?
event type: touch
direction: down
currency: BTC
required strike: 15000.0
iv: 0.9241177899343831
buy_yes_ev: -0.0008918061851654023
sell_yes_ev: -0.002515283814834594
buy_no_ev: -0.002515283814834535
sell_no_ev: -0.0008918061851654058
buy_yes_kelly: -0.00045464932717739743
sell_yes_kelly: -0.07944558654026486
buy_no_kelly: -0.07944558654026272
sell_no_kelly: -0.0004546493271773992

,id,question,endDate,yes_ask,no_ask,model_prob,conditionId,slug,resolutionSource,liquidity,...,buy_yes_ev,sell_yes_ev,buy_no_ev,sell_no_ev,buy_yes_kelly,sell_yes_kelly,buy_no_kelly,sell_no_kelly,best_ev,best_action
743,701552,"Will Ethereum dip to $1,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.402,0.599,0.522990,0xcf25ccc8360f3952139fb5e3f14cb9bb0636cb53d0e3...,will-ethereum-dip-to-1500-by-december-31-2026-...,,70257.75215,...,0.104162,-0.138804,-0.138804,0.104162,0.089614,-0.180647,-0.180647,0.089614,0.104162,buy_yes_ev
729,701502,"Will Bitcoin dip to $45,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.22,0.79,0.288855,0x024b68f77bfc019341ee3db8f57c103334e4b9430bba...,will-bitcoin-dip-to-45000-by-december-31-2026-...,,164897.6908,...,0.056843,-0.090468,-0.090468,0.056843,0.037008,-0.228010,-0.228010,0.037008,0.056843,buy_yes_ev
728,701501,"Will Bitcoin dip to $55,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.54,0.47,0.592828,0x752fa61c93f16c4b15e85b0bd438d9c684176b0ea7b3...,will-bitcoin-dip-to-55000-by-december-31-2026-...,,99844.3352,...,0.035440,-0.080265,-0.080265,0.035440,0.040036,-0.078298,-0.078298,0.040036,0.035440,buy_yes_ev
730,701503,"Will Bitcoin dip to $35,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.1,0.91,0.141137,0x2745c38ff0617cb345c1d2df19b4f74ea777508e0741...,will-bitcoin-dip-to-35000-by-december-31-2026-...,,109998.0282,...,0.034837,-0.056870,-0.056870,0.034837,0.019490,-0.337439,-0.337439,0.019490,0.034837,sell_no_ev
731,701504,"Will Bitcoin dip to $25,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.032,0.971,0.067107,0xe326d1abf5fb59b82ecfdff3348e75f90561eace327b...,will-bitcoin-dip-to-25000-by-december-31-2026-...,,112247.15921,...,0.032939,-0.040078,-0.040078,0.032939,0.017052,-0.741394,-0.741394,0.017052,0.032939,buy_yes_ev

In [14]:
opportunities_df

,id,question,endDate,yes_ask,no_ask,model_prob,conditionId,slug,resolutionSource,liquidity,...,buy_yes_ev,sell_yes_ev,buy_no_ev,sell_no_ev,buy_yes_kelly,sell_yes_kelly,buy_no_kelly,sell_no_kelly,best_ev,best_action
585,701552,"Will Ethereum dip to $1,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.402,0.599,0.525600,0xcf25ccc8360f3952139fb5e3f14cb9bb0636cb53d0e3...,will-ethereum-dip-to-1500-by-december-31-2026-...,,80206.24887,...,0.106772,-0.141414,-0.141414,0.106772,0.091859,-0.184044,-0.184044,0.091859,0.106772,buy_yes_ev
571,701502,"Will Bitcoin dip to $45,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.22,0.79,0.290404,0x024b68f77bfc019341ee3db8f57c103334e4b9430bba...,will-bitcoin-dip-to-45000-by-december-31-2026-...,,176419.5778,...,0.058392,-0.092017,-0.092017,0.058392,0.038016,-0.231913,-0.231913,0.038016,0.058392,buy_yes_ev
570,701501,"Will Bitcoin dip to $55,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.54,0.47,0.596012,0x752fa61c93f16c4b15e85b0bd438d9c684176b0ea7b3...,will-bitcoin-dip-to-55000-by-december-31-2026-...,,109562.3945,...,0.038624,-0.083449,-0.083449,0.038624,0.043631,-0.081403,-0.081403,0.043631,0.038624,buy_yes_ev
572,701503,"Will Bitcoin dip to $35,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.1,0.91,0.142061,0x2745c38ff0617cb345c1d2df19b4f74ea777508e0741...,will-bitcoin-dip-to-35000-by-december-31-2026-...,,121810.5132,...,0.035761,-0.057794,-0.057794,0.035761,0.020007,-0.342919,-0.342919,0.020007,0.035761,sell_no_ev
573,701504,"Will Bitcoin dip to $25,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.032,0.971,0.067666,0xe326d1abf5fb59b82ecfdff3348e75f90561eace327b...,will-bitcoin-dip-to-25000-by-december-31-2026-...,,119892.99113,...,0.033497,-0.040637,-0.040637,0.033497,0.017341,-0.751729,-0.751729,0.017341,0.033497,buy_yes_ev
586,701553,"Will Ethereum dip to $1,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.12,0.9,0.154152,0xacb33346b59a2a3770e2391b7d1b0e77d8dcdcf840a6...,will-ethereum-dip-to-1000-by-december-31-2026-...,,107512.879,...,0.026760,-0.060452,-0.060452,0.026760,0.015333,-0.322581,-0.322581,0.015333,0.026760,sell_no_ev
582,701547,"Will Ethereum reach $4,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.05,0.96,0.011920,0xa3143f9c21ecc7a9b036b4e435f48264ff72019a9e3e...,will-ethereum-reach-4500-by-december-31-2026,,44865.9755,...,-0.041405,0.025392,0.025392,-0.041405,-0.021868,0.340260,0.340260,-0.021868,0.025392,buy_no_ev
580,701545,"Will Ethereum reach $5,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.032,0.969,0.004079,0xb75b8c777c5fd934d7fa43d4b3a3f630981b68a362a0...,will-ethereum-reach-5500-by-december-31-2026,,32265.63124,...,-0.030089,0.024818,0.024818,-0.030089,-0.015577,0.429418,0.429418,-0.015577,0.024818,sell_yes_ev
583,701548,"Will Ethereum reach $4,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.06,0.95,0.023267,0x9775cd557a3cdba4f0478070afa399c0805761dd9aa0...,will-ethereum-reach-4000-by-december-31-2026,,41181.0932,...,-0.040681,0.023408,0.023408,-0.040681,-0.021730,0.250750,0.250750,-0.021730,0.023408,buy_no_ev
567,701494,"Will Bitcoin reach $120,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.05,0.96,0.014509,0xf9b6b5c3c6e07afe4aad6ed9ce4fa7545f9c2baa9f1d...,will-bitcoin-reach-120000-by-december-31-2026-...,,52908.6704,...,-0.038816,0.022803,0.022803,-0.038816,-0.020501,0.305571,0.305571,-0.020501,0.022803,buy_no_ev
581,701546,"Will Ethereum reach $5,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.039,0.969,0.006911,0x1c4fd67ab2a67f508672a69153559911244048b79a40...,will-ethereum-reach-5000-by-december-31-2026,,27878.72694,...,-0.034713,0.021987,0.021987,-0.034713,-0.018110,0.380426,0.380426,-0.018110,0.021987,sell_yes_ev
566,701493,"Will Bitcoin reach $130,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.034,0.967,0.009119,0x885a6abefad122348b4fbd503473d7fd1f9035d0438c...,will-bitcoin-reach-130000-by-december-31-2026-...,,76867.63011,...,-0.027180,0.021648,0.021648,-0.027180,-0.014102,0.351807,0.351807,-0.014102,0.021648,sell_yes_ev
565,701492,"Will Bitcoin reach $140,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.03,0.971,0.005463,0xf0a4c0bc8a8162f0ac95b5a5af7fa665d20a19ca0db0...,will-bitcoin-reach-140000-by-december-31-2026-...,,75293.19074,...,-0.026574,0.021566,0.021566,-0.026574,-0.013727,0.398948,0.398948,-0.013727,0.021566,sell_yes_ev
578,701543,"Will Ethereum reach $6,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.026,0.975,0.001875,0x0f0499d1049385b1d53ffee6c42a1de7424e551c7652...,will-ethereum-reach-6500-by-december-31-2026,,42854.24209,...,-0.025898,0.021419,0.021419,-0.025898,-0.013319,0.459751,0.459751,-0.013319,0.021419,sell_yes_ev
577,701542,"Will Ethereum reach $7,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.025,0.976,0.000953,0x4ee2c6081e18cc0d1f3347f6219940bda986657f1d15...,will-ethereum-reach-7000-by-december-31-2026,,60874.46522,...,-0.025754,0.021408,0.021408,-0.025754,-0.013230,0.478701,0.478701,-0.013230,0.021408,sell_yes_ev
563,701490,"Will Bitcoin reach $160,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.026,0.975,0.002543,0x472c9035786b390c08e674fc60bddda488957e1b8aec...,will-bitcoin-reach-160000-by-december-31-2026-...,,69755.41507,...,-0.025229,0.020750,0.020750,-0.025229,-0.012975,0.445408,0.445408,-0.012975,0.020750,sell_yes_ev
579,701544,"Will Ethereum reach $6,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.03,0.975,0.002718,0x6132cc91f7a0ad656e890b9040c159f4057f4c44359b...,will-ethereum-reach-6000-by-december-31-2026,,40790.16089,...,-0.029319,0.020576,0.020576,-0.029319,-0.015145,0.441654,0.441654,-0.015145,0.020576,sell_yes_ev
576,701541,"Will Ethereum reach $7,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.024,0.977,0.001085,0x4fc8725f00ba06576d7c78131e4589cc93a4e133128e...,will-ethereum-reach-7500-by-december-31-2026,,69860.28928,...,-0.024555,0.020342,0.020342,-0.024555,-0.012600,0.474683,0.474683,-0.012600,0.020342,buy_no_ev
568,701495,"Will Bitcoin reach $110,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.06,0.95,0.027847,0x63eaf41ce1f475323e2202d7dfa3b1def8b82cd166f7...,will-bitcoin-reach-110000-by-december-31-2026-...,,69202.1122,...,-0.036101,0.018828,0.018828,-0.036101,-0.019283,0.201688,0.201688,-0.019283,0.018828,buy_no_ev
564,701491,"Will Bitcoin reach $150,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.025,0.976,0.004119,0xa7b594ae07d5c1590fa86028fcc2f870599043723741...,will-bitcoin-reach-150000-by-december-31-2026-...,,87664.09132,...,-0.022587,0.018241,0.018241,-0.022587,-0.011603,0.407892,0.407892,-0.011603,0.018241,sell_yes_ev
560,701487,"Will Bitcoin reach $190,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.021,0.98,0.001090,0xe71b9d788ce662d967ff2c90749ff8b26cee290455ef...,will-bitcoin-reach-190000-by-december-31-2026-...,,82744.08998,...,-0.021349,0.017538,0.017538,-0.021349,-0.010919,0.470737,0.470737,-0.010919,0.017538,sell_yes_ev
562,701489,"Will Bitcoin reach $170,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.022,0.979,0.002343,0x9affeb38bce1e9a6de30e9ecada1ecfaf636574d3961...,will-bitcoin-reach-170000-by-december-31-2026-...,,73919.50325,...,-0.021163,0.017217,0.017217,-0.021163,-0.010836,0.440099,0.440099,-0.010836,0.017217,buy_no_ev
575,701540,"Will Ethereum reach $8,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.02,0.982,0.000796,0xac0b4316113b50e0e667918aee72fa0eb006342245a5...,will-ethereum-reach-8000-by-december-31-2026,,65365.66369,...,-0.020576,0.015967,0.015967,-0.020576,-0.010513,0.476267,0.476267,-0.010513,0.015967,buy_no_ev
561,701488,"Will Bitcoin reach $180,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.021,0.981,0.001739,0x799c35de1e5f3ebd75053643e020e6df9e9a3f477e3d...,will-bitcoin-reach-180000-by-december-31-2026-...,,59222.68052,...,-0.020700,0.015956,0.015956,-0.020700,-0.010587,0.450849,0.450849,-0.010587,0.015956,buy_no_ev
559,701486,"Will Bitcoin reach $200,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.018,0.983,0.000769,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,will-bitcoin-reach-200000-by-december-31-2026-...,,82737.69945,...,-0.018469,0.015062,0.015062,-0.018469,-0.009415,0.475723,0.475723,-0.009415,0.015062,buy_no_ev
829,1057883,"Will Bitcoin reach $250,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.017,0.984,0.000119,0x6fefc0438c7598b23531457c8c60541990d0786bd4bd...,will-bitcoin-reach-250000-by-december-31-2026-...,,101479.60688,...,-0.018051,0.014779,0.014779,-0.018051,-0.009192,0.496000,0.496000,-0.009192,0.014779,buy_no_ev
584,701549,"Will Ethereum reach $3,500 by December 31, 2026?",2027-01-01T05:00:00Z,0.08,0.93,0.052297,0x42945ea5657d6f6e77969a06661b29d6f6295083d1ef...,will-ethereum-reach-3500-by-december-31-2026,,47996.3013,...,-0.032855,0.013146,0.013146,-0.032855,-0.017957,0.100441,0.100441,-0.017957,0.013146,sell_yes_ev
587,701554,"Will Ethereum dip to $800 by December 31, 2026?",2027-01-01T05:00:00Z,0.07,0.94,0.085975,0x717672a48c5f2938631f6e467b9a48aedb03fa380c01...,will-ethereum-dip-to-800-by-december-31-2026-568,,91141.563,...,0.011418,-0.029923,-0.029923,0.011418,0.006169,-0.266918,-0.266918,0.006169,0.011418,sell_no_ev
574,701539,"Will Ethereum reach $10,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.011,0.99,0.000188,0x201f51d2d892c41c5bfa6568a0a2f93ab2ea426e87dd...,will-ethereum-reach-10000-by-december-31-2026,,63732.62355,...,-0.011573,0.009119,0.009119,-0.011573,-0.005855,0.489886,0.489886,-0.005855,0.009119,sell_yes_ev
166,573656,"Will Bitcoin hit $150k by December 31, 2026?",2027-01-01T05:00:00Z,0.013,0.988,0.004119,0x02deb9538f5c123373adaa4ee6217b01745f1662bc90...,will-bitcoin-hit-150k-by-december-31-2026,,207965.20826,...,-0.009779,0.007051,0.007051,-0.009779,-0.004958,0.315619,0.315619,-0.004958,0.007051,sell_yes_ev
569,701496,"Will Bitcoin reach $100,000 by December 31, 2026?",2027-01-01T05:00:00Z,0.08,0.93,0.058468,0xdaa4866bae18be58c5a79d2aeeffd035ec78f1bb49db...,will-bitcoin-reach-100000-by-december-31-2026-...,,95389.2041,...,-0.026684,0.006975,0.006975,-0.026684,-0.014584,0.053288,0.053288,-0.014584,0.006975,sell_yes_ev

In [15]:
# 12. manage cancel orders
orders_df = portfolio.manage_open_orders(api=api, orders_df=orders_df, markets_df=markets_df, 
                ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)
orders_df

STATUS: 502
RESPONSE: {"detail":"Polymarket CLOB error: Request exception!"}
REQUEST URL: https://alphasignal-dev.moretoncp.com/v1/orders
REQUEST BODY: None
REQUEST PARAMS: {}

HTTPError: 502 Server Error: Bad Gateway for url: https://alphasignal-dev.moretoncp.com/v1/orders

In [16]:
# 13. Risk management
orders_df = portfolio.run_risk_management(api=api, positions_df=positions_df, 
            markets_df=markets_df, orders_df=orders_df, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

pos: condition_id         0xa3143f9c21ecc7a9b036b4e435f48264ff72019a9e3e...
token_id             4251240413067872674686064123803499349976238079...
outcome                                                             No
shares                                                            4.95
cost_basis                                                       4.752
avg_entry_price                                                   0.96
realized_pnl                                                       0.0
realized_shares                                                    0.0
realized_fees                                                      0.0
current_price                                                     0.95
market_value                                                    4.7025
unrealized_pnl                                                 -0.0495
unrealized_return                                            -0.010417
Name: 0, dtype: object
market: id                                                          701547
question          Will Ethereum reach $4,500 by December 31, 2026?
endDate                                       2027-01-01T05:00:00Z
yes_ask                                                       0.05
no_ask                                                        0.96
                                        ...
sell_yes_kelly                                            0.337653
buy_no_kelly                                              0.337653
sell_no_kelly                                            -0.021766
best_ev                                                   0.025197
best_action                                              buy_no_ev
Name: 740, Length: 133, dtype: object
======================================================================
                             HOLD SIGNAL
======================================================================
Market                    : Will Ethereum reach $4,500 by December 31, 2026?
Outcome                   : No
Direction                 : up
Event Type                : touch
Best Action               : HOLD
Current Bid               : 0.95
Current Shares            : 4.95
P Yes                     : 0.01211495505278002
P No                      : 0.98788504494722
Exit EV                   : 0.9466749999999999
Hold EV                   : 0.98788504494722
Fee Rate                  : 0.07
Unrealized Pnl            : -0.0495000000000001
Unrealized Return         : -0.010416666666666689
Exit EV threshold         : 0.02
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 4251240413067872674686064123803499349976238079777545616008767482027755117695
orderPrice                : 0.95
orderSize                 : 4.95
clientOrderId             : 5820cde8-2982-4c84-95c5-a4a2ded82edd
======================================================================
pos: condition_id         0xb75b8c777c5fd934d7fa43d4b3a3f630981b68a362a0...
token_id             4479131210875376621873271572183009281689857070...
outcome                                                             No
shares                                                            4.91
cost_basis                                                     4.75779
avg_entry_price                                                  0.969
realized_pnl                                                       0.0
realized_shares                                                    0.0
realized_fees                                                      0.0
current_price                                                    0.968
market_value                                                   4.75288
unrealized_pnl                                                -0.00491
unrealized_return                                            -0.001032
Name: 1, dtype: object
market: id                                                          701545
question          Will Ethereum reach $5,500 by December 31, 2026?
endDate                                       2027-01-01T05:00:00Z
yes_ask                                                      0.032
no_ask                                                       0.969
                                        ...
sell_yes_kelly                                            0.428053
buy_no_kelly                                              0.428053
sell_no_kelly                                            -0.015536
best_ev                                                   0.024739
best_action                                            sell_yes_ev
Name: 738, Length: 133, dtype: object
======================================================================
                             HOLD SIGNAL
======================================================================
Market                    : Will Ethereum reach $5,500 by December 31, 2026?
Outcome                   : No
Direction                 : up
Event Type                : touch
Best Action               : HOLD
Current Bid               : 0.968
Current Shares            : 4.91
P Yes                     : 0.004158153118090197
P No                      : 0.9958418468819098
Exit EV                   : 0.96583168
Hold EV                   : 0.9958418468819098
Fee Rate                  : 0.07
Unrealized Pnl            : -0.004909999999999748
Unrealized Return         : -0.0010319917440659945
Exit EV threshold         : 0.02
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 447913121087537662187327157218300928168985707076581166939650812231975265268
orderPrice                : 0.968
orderSize                 : 4.91
clientOrderId             : db7c2972-5b86-4156-9aee-e634ae20e24b
======================================================================
pos: condition_id         0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...
token_id             9699347185440015640867052761315094444335927219...
outcome                                                             No
shares                                                            4.87
cost_basis                                                     4.77747
avg_entry_price                                                  0.981
realized_pnl                                                       0.0
realized_shares                                                    0.0
realized_fees                                                      0.0
current_price                                                    0.982
market_value                                                   4.78234
unrealized_pnl                                                 0.00487
unrealized_return                                             0.001019
Name: 2, dtype: object
market: id                                                           701486
question          Will Bitcoin reach $200,000 by December 31, 2026?
endDate                                        2027-01-01T05:00:00Z
yes_ask                                                       0.018
no_ask                                                        0.983
                                        ...
sell_yes_kelly                                             0.475267
buy_no_kelly                                               0.475267
sell_no_kelly                                             -0.009408
best_ev                                                    0.015047
best_action                                               buy_no_ev
Name: 717, Length: 133, dtype: object
======================================================================
                             HOLD SIGNAL
======================================================================
Market                    : Will Bitcoin reach $200,000 by December 31, 2026?
Outcome                   : No
Direction                 : up
Event Type                : touch
Best Action               : HOLD
Current Bid               : 0.982
Current Shares            : 4.87
P Yes                     : 0.0007830634177411252
P No                      : 0.9992169365822589
Exit EV                   : 0.98076268
Hold EV                   : 0.9992169365822589
Fee Rate                  : 0.07
Unrealized Pnl            : 0.004869999999999486
Unrealized Return         : 0.0010193679918449484
Exit EV threshold         : 0.02
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 96993471854400156408670527613150944443359272190785251193551242374636006072800
orderPrice                : 0.982
orderSize                 : 4.87
clientOrderId             : d47c0b91-869a-4908-a6cb-4e8599c0c52d
======================================================================

In [16]:
# 14. New opportunities
orders_df = portfolio.run_new_opportunities(api=api, opportunities_df=opportunities_df, orders_df=orders_df, 
            ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, MAX_POSITION=MAX_POSITION, FRACTION=FRACTION)

current balance size: 0.0
dollars: 2.1866264638395267
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum dip to $1,500 by December 31, 2026?
Outcome                   : YES
Direction                 : down
Event Type                : touch
Best Action               : buy_yes_ev
Kelly Size x Fraction     : 0.022964862314782286
Recommended Size          : 5.439369
Current Ask               : 0.402
P Yes                     : 0.5256000511309448
P No                      : 0.47439994886905523
Buy Yes EV                : 0.10677233113094478
Sell No EV                : 0.10677233113094478
Buy No EV                 : -0.14141398113094472
Sell Yes EV               : -0.14141398113094472
Unrealized Pnl            : 0.580774108011396
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 101639751789549589765350117072740510018809594718571111931328241076831078702528
orderPrice                : 0.402
orderSize                 : 5.439369
clientOrderId             : 77b5e9db-a19a-48f7-9b92-d9240b452a80
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
Order too small after position cap, skipping, dollars: 0.9049431527736957
current balance size: 0.0
dollars: 1.0386046207574462
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Bitcoin dip to $55,000 by December 31, 2026?
Outcome                   : YES
Direction                 : down
Event Type                : touch
Best Action               : buy_yes_ev
Kelly Size x Fraction     : 0.010907858525278437
Recommended Size          : 1.923342
Current Ask               : 0.54
P Yes                     : 0.5960115926207243
P No                      : 0.40398840737927566
Buy Yes EV                : 0.03862359262072432
Sell No EV                : 0.03862359262072432
Buy No EV                 : -0.08344859262072427
Sell Yes EV               : -0.08344859262072435
Unrealized Pnl            : 0.07428637787832916
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 115462087336983275104521488923966022755348986822352694745153736621832003960847
orderPrice                : 0.54
orderSize                 : 1.923342
clientOrderId             : 35dcab0d-4cc2-47c1-bd6e-949adb7d7a44
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
Order too small after position cap, skipping, dollars: 0.4762483288038256
current balance size: 0.0
Order too small after position cap, skipping, dollars: 0.41279045491624644
current balance size: 0.0
Order too small after position cap, skipping, dollars: 0.36499189039124275
current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $4,500 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.08506495302275262
Recommended Size          : 4.959176
Current Ask               : 0.96
P Yes                     : 0.01192045178252044
P No                      : 0.9880795482174796
Buy Yes EV                : -0.04140454821747957
Sell No EV                : -0.04140454821747963
Buy No EV                 : 0.025391548217479572
Sell Yes EV               : 0.02539154821747956
Unrealized Pnl            : 0.12592115652296748
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 4251240413067872674686064123803499349976238079777545616008767482027755117695
orderPrice                : 0.96
orderSize                 : 4.959176
clientOrderId             : be29817f-3d8f-423e-b6e2-0a94f894d65c
======================================================================

LIMIT ORDER SUBMITTED


{'order_id': '01a01909-73d4-7d70-b257-86624e8fc697', 'clob_order_id': '0x387e06d4de5bb3110d135297db63ce667c4a3ac0de7dd3ca8eb16cd7b5e89547', 'status': 'submitted', 'clob_status': 'matched', 'error_message': None, 'replayed': False}

LIMIT ORDER RECORDED


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $5,500 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.10735439045607363
Recommended Size          : 4.913116
Current Ask               : 0.969
P Yes                     : 0.0040792795464433314
P No                      : 0.9959207204535566
Buy Yes EV                : -0.03008904045355667
Sell No EV                : -0.030089040453556697
Buy No EV                 : 0.024817990453556642
Sell Yes EV               : 0.024817990453556666
Unrealized Pnl            : 0.12193366598521638
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 447913121087537662187327157218300928168985707076581166939650812231975265268
orderPrice                : 0.969
orderSize                 : 4.913116
clientOrderId             : f768eb76-58fc-4a96-b876-74fa06f9b443
======================================================================

LIMIT ORDER SUBMITTED


{'order_id': '01a01909-c882-7ab3-99b0-15a8769185da', 'clob_order_id': '0xf7ff5b16da1bb114dc0b34d7e83324beb8b85502f0290898235ea18753209b32', 'status': 'submitted', 'clob_status': 'matched', 'error_message': None, 'replayed': False}

LIMIT ORDER RECORDED


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $4,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.06268758041360978
Recommended Size          : 5.011378
Current Ask               : 0.95
P Yes                     : 0.02326745747355812
P No                      : 0.9767325425264419
Buy Yes EV                : -0.04068054252644189
Sell No EV                : -0.04068054252644189
Buy No EV                 : 0.0234075425264419
Sell Yes EV               : 0.02340754252644188
Unrealized Pnl            : 0.11730404365107536
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 24395525485845393350950214688967223293165153127110039869504787811540919959137
orderPrice                : 0.95
orderSize                 : 5.011378
clientOrderId             : 5ac8cfaa-13e5-4959-9863-3bb78928f0de
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Bitcoin reach $120,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.07639263271338965
Recommended Size          : 4.959176
Current Ask               : 0.96
P Yes                     : 0.014509104705584041
P No                      : 0.9854908952944159
Buy Yes EV                : -0.03881589529441596
Sell No EV                : -0.03881589529441602
Buy No EV                 : 0.022802895294415967
Sell Yes EV               : 0.022802895294415954
Unrealized Pnl            : 0.1130835710745806
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 23087349975908951689849809689657583268158750956541808535385269508170739441669
orderPrice                : 0.96
orderSize                 : 4.959176
clientOrderId             : 8979f8fa-2982-4f9c-babd-dd447643e44e
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $5,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.09510658010747707
Recommended Size          : 4.913116
Current Ask               : 0.969
P Yes                     : 0.006910705806860848
P No                      : 0.9930892941931392
Buy Yes EV                : -0.034712824193139154
Sell No EV                : -0.03471282419313923
Buy No EV                 : 0.02198656419313913
Sell Yes EV               : 0.021986564193139154
Unrealized Pnl            : 0.10802254032233893
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 83653530246789118994492246634339447976331394500468058931341870541635471603330
orderPrice                : 0.969
orderSize                 : 4.913116
clientOrderId             : e8efbbce-83bc-4801-8fc0-1845bec717e2
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Bitcoin reach $130,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.08795185666183801
Recommended Size          : 4.923277
Current Ask               : 0.967
P Yes                     : 0.009118653592118879
P No                      : 0.9908813464078812
Buy Yes EV                : -0.027180426407881125
Sell No EV                : -0.02718042640788116
Buy No EV                 : 0.021647576407881126
Sell Yes EV               : 0.021647576407881126
Unrealized Pnl            : 0.10657701503466376
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 112640187121872104723655834799934821712465419714201363140089615513884600316497
orderPrice                : 0.967
orderSize                 : 4.923277
clientOrderId             : 71f8ad30-171d-42d6-9a26-9831937f7bac
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Bitcoin reach $140,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.09973696633187962
Recommended Size          : 4.902996
Current Ask               : 0.971
P Yes                     : 0.005462650022569989
P No                      : 0.99453734997743
Buy Yes EV                : -0.026574349977430006
Sell No EV                : -0.02657434997742999
Buy No EV                 : 0.021566219977429996
Sell Yes EV               : 0.021566219977430013
Unrealized Pnl            : 0.10573909028445935
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 70543103071492972645151283689391729699226843216132833577173691542490654530110
orderPrice                : 0.971
orderSize                 : 4.902996
clientOrderId             : c4c44c60-0ce7-4dd8-bae4-fff971f71892
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $6,500 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.11493783385407536
Recommended Size          : 4.882881
Current Ask               : 0.975
P Yes                     : 0.0018750846612930585
P No                      : 0.998124915338707
Buy Yes EV                : -0.02589759533870694
Sell No EV                : -0.025897595338706936
Buy No EV                 : 0.021418665338706944
Sell Yes EV               : 0.021418665338706944
Unrealized Pnl            : 0.10458479402773072
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 3795456661398758630605539351146269210817563620320500341129812236254954598954
orderPrice                : 0.975
orderSize                 : 4.882881
clientOrderId             : 206bcd94-f820-4fdb-8586-9fc739a61c41
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $7,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.11967517253250697
Recommended Size          : 4.877878
Current Ask               : 0.976
P Yes                     : 0.0009525187689434726
P No                      : 0.9990474812310566
Buy Yes EV                : -0.02575373123105653
Sell No EV                : -0.02575373123105657
Buy No EV                 : 0.02140780123105652
Sell Yes EV               : 0.021407801231056525
Unrealized Pnl            : 0.1044246426533435
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 75288143604803732314838829042251947353307124881100168459667426665993043332752
orderPrice                : 0.976
orderSize                 : 4.877878
clientOrderId             : de0f9c9b-e335-4fca-a2e9-39e04b230286
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Bitcoin reach $160,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.11135197580409051
Recommended Size          : 4.882881
Current Ask               : 0.975
P Yes                     : 0.0025433093089077324
P No                      : 0.9974566906910922
Buy Yes EV                : -0.025229370691092264
Sell No EV                : -0.02522937069109226
Buy No EV                 : 0.02075044069109227
Sell Yes EV               : 0.02075044069109227
Unrealized Pnl            : 0.10132193259216131
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST
tokenId                   : 76803677654662369423401526996593319593052274118670807871700313758063944314185
orderPrice                : 0.975
orderSize                 : 4.882881
clientOrderId             : 1ab87986-b89e-4504-bcae-429818fc4b70
======================================================================

LIMIT SKIPPING ORDER


current balance size: 0.0
dollars: 4.760809
======================================================================
BUY SIGNAL
======================================================================
Market                    : Will Ethereum reach $6,000 by December 31, 2026?
Outcome                   : NO
Direction                 : up
Event Type                : touch
Best Action               : buy_no_ev
Kelly Size x Fraction     : 0.110413431642586
Recommended Size          : 4.882881
Current Ask               : 0.975
P Yes                     : 0.0027182070134040962
P No                      : 0.9972817929865959
Buy Yes EV                : -0.0293187929865959
Sell No EV                : -0.029318792986595885
Buy No EV                 : 0.020575542986595904
Sell Yes EV               : 0.020575542986595904
Unrealized Pnl            : 0.1004679279139324
Cash                      : 95.21618
Current Shares            : 0.0
Fee Rate                  : 0.07
ENTRY EV THRESHOLD        : 0.02
MAX POSITION THRESHOLD    : 0.05
======================================================================
                         VARIABLES IN REQUEST

In [45]:
# 15. Safe dfs
portfolio.save_snapshots(DATA_DIR, markets_df, "markets")
portfolio.save_snapshots(DATA_DIR, opportunities_df, "opportunities")
portfolio.save(DATA_DIR, orders_df, "orders")
portfolio.save(DATA_DIR, fills_df, "fills")
portfolio.save(DATA_DIR, positions_df, "positions")
portfolio.save(DATA_DIR, realized_pnl_df, "realized_pnl")
portfolio.save(DATA_DIR, equity_df, "equity")

save_snapshots df saved at: data/20260819/markets_20260819_165010.parquet
save_snapshots df saved at: data/20260819/opportunities_20260819_165010.parquet
save df saved at:  data/orders.parquet
save df saved at:  data/fills.parquet
save df saved at:  data/positions.parquet
save df saved at:  data/realized_pnl.parquet
save df saved at:  data/equity.parquet

In [ ]:
# BACKTEST

# # 13. Risk management
# orders_df_backtest = portfolio.run_risk_management_test(api=api, positions_df=positions_df_backtest, 
#             markets_df=markets_df_backtest, orders_df=orders_df_backtest, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

# # 14. New opportunities
# orders_df_backtest = portfolio.run_new_opportunities_test(api=api, opportunities_df=opportunities_df_backtest, orders_df=orders_df_backtest, 
#             ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, MAX_POSITION=MAX_POSITION, FRACTION=FRACTION)

# # 15. Safe dfs
# portfolio.save_snapshots(DATA_DIR, markets_df_backtest, "markets_backtest")
# portfolio.save_snapshots(DATA_DIR, opportunities_df_backtest, "opportunities_backtest")
# portfolio.save(DATA_DIR, orders_df_backtest, "orders_backtest")
# portfolio.save(DATA_DIR, fills_df_backtest, "fills_backtest")
# portfolio.save(DATA_DIR, positions_df_backtest, "positions_backtest")
# portfolio.save(DATA_DIR, realized_pnl_df_backtest, "realized_pnl_backtest")
# portfolio.save(DATA_DIR, equity_df_backtest, "equity_backtest")

In [ ]:
ENTRY_EV_THRESHOLD = 0.02   # require 1% edge, default = 0
EXIT_EV_THRESHOLD = 0.02
FRACTION = 0.25
MAX_POSITION = 0.05

load_dotenv(r"D:/OneDrive/Trading/Prediction Markets/Moreton Capital/.env")
BASE_URL = os.getenv("BASE_URL")
USER_EMAIL = os.getenv("USER_EMAIL")
USER_PASSWORD = os.getenv("USER_PASSWORD")
JWT_TOKEN = os.getenv("JWT")
DATA_DIR = os.getenv("DATA_DIR")
print(BASE_URL)

with open(f"{DATA_DIR}/crypto_tag_ids.json", "r") as f:
    crypto_tag_ids = set(json.load(f))

s = OptionSurface()
portfolio = Portfolio()
api = TradingDeskAPI(base_url=BASE_URL, email=USER_EMAIL, password=USER_PASSWORD, token=JWT_TOKEN)
scanner = MarketScanner(api=api)

target_expiry_str = "25DEC26"
target_expiry = datetime.strptime(target_expiry_str, "%d%b%y").strftime("%Y%m%d")

currencies = ["BTC", "ETH"]

for i in range(1):
    # 1. Get all dfs
    orders_df = pd.read_parquet(f"{DATA_DIR}/orders.parquet")
    fills_df = pd.read_parquet(f"{DATA_DIR}/fills.parquet")
    positions_df = pd.read_parquet(f"{DATA_DIR}/positions.parquet")
    equity_df = pd.read_parquet(f"{DATA_DIR}/equity.parquet")

    # 2. Get newly executed trades
    fills_df = portfolio.sync_fills(api=api, fills_df=fills_df)

    # 3. Reconstruct portfolio
    # 4. Calculate realized P&L
    positions_df, realized_pnl_df = portfolio.reconstruct_positions_fifo(fills_df=fills_df) # new realized_df to overwrite old

    # 5. Sync positions with api
    portfolio.reconcile_positions(api=api, positions_df=positions_df)

    # 6. Get latest order state
    orders_df = portfolio.sync_orders(api=api, orders_df=orders_df)

    # 7. Mark positions to market
    positions_df = portfolio.mark_positions_to_market(api=api, positions_df=positions_df)

    # 8. Calculate equity
    equity_df = portfolio.calculate_equity(api=api, positions_df=positions_df, 
                                    realized_pnl_df=realized_pnl_df, equity_df=equity_df)

    # 9. Get current markets
    all_markets_df = api.get_all_markets(DATA_DIR=DATA_DIR, count_limit=10, liquidity_num_min=10000, volume_num_min=5000)

    # 10. Initialize variance surface
    deribit = Deribit(currencies=currencies, target_expiry=target_expiry)
    okx = OKX(currencies=currencies, target_expiry=target_expiry)
    bybit = Bybit(currencies=currencies, target_expiry=target_expiry)

    s.initialize(currencies=currencies, exchanges=[deribit, okx, bybit])

    # 11. Scan markets
    markets_df, opportunities_df = scanner.scan_market(markets_df=all_markets_df, s=s, crypto_tag_ids=crypto_tag_ids)

    # 12. manage cancel orders
    orders_df = portfolio.manage_open_orders(api=api, orders_df=orders_df, markets_df=markets_df, 
                ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

    # 13. Risk management
    orders_df = portfolio.run_risk_management(api=api, positions_df=positions_df, 
            markets_df=markets_df, orders_df=orders_df, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

    # 14. New opportunities
    orders_df = portfolio.run_new_opportunities(api=api, opportunities_df=opportunities_df, orders_df=orders_df, 
            ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, MAX_POSITION=MAX_POSITION, FRACTION=FRACTION)

    # 15. Safe dfs
    portfolio.save_snapshots(DATA_DIR, markets_df, "markets")
    portfolio.save_snapshots(DATA_DIR, opportunities_df, "opportunities")
    portfolio.save(DATA_DIR, orders_df, "orders")
    portfolio.save(DATA_DIR, fills_df, "fills")
    portfolio.save(DATA_DIR, positions_df, "positions")
    portfolio.save(DATA_DIR, realized_pnl_df, "realized_pnl")
    portfolio.save(DATA_DIR, equity_df, "equity")

    # time.sleep(300)

In [ ]:
# Polymarket    Model (exchanges: deribit, bybit, okx)    Edge

# 80k Dec-26        22%          20%       +2%
# 90k Dec-26        14%          12%       +2%
# 100k Dec-26        9.5%         5.9%     +3.6%
# 110k Dec-26        7%           4%       +3%
# 120k Dec-26        5%           2%       +3%

In [ ]:
# Keep trading journal

# Your thesis.
# Why you think the market is mispriced.
# Position size.
# Exit criteria.
# What actually happened.

In [ ]:
# Stage 2 — Semi-automated execution

# The bot does:

# find opportunities
# calculate size
# prepare orders

# You approve:

# BUY YES
# Market: BTC above $150k
# Price: 0.43
# Size: $500
# Expected edge: +8%

# Click "confirm".

# This is useful because prediction markets can have:

# ambiguous wording
# resolution risks
# sudden news events

In [ ]:
# Day 1 — API connection + market ingestion

# Goal:

# Can I pull markets automatically?

# Build:

# get_markets()

# Output:

# {
#  "condition_id": "...",
#  "question": "Will X happen?",
#  "tokens": [
#     {
#       "token_id": "YES",
#       "price": 0.42
#     },
#     {
#       "token_id": "NO",
#       "price": 0.58
#     }
#  ]
# }

# Store:

# markets

# condition_id
# question
# yes_token
# no_token
# created_time
# Day 2 — Historical snapshots

# Goal:

# Can I reconstruct what the market looked like yesterday?

# Every 5 minutes:

# while True:

#     markets = api.get_markets()

#     for m in markets:
#         database.save_snapshot(m)

#     sleep(300)

# Database:

# market_snapshots

# timestamp
# condition_id
# yes_price
# no_price
# volume
# Day 3 — Order book collection

# Now collect microstructure data.

# For selected markets:

# get_orderbook(token_id)

# Store:

# orderbook_snapshots

# timestamp

# token_id

# best_bid
# best_ask

# bid_depth
# ask_depth

# Calculate:

# Spread
# spread=ask−bid

# Example:

# Bid:
# 0.42

# Ask:
# 0.46

# Spread:
# 4 cents
# Day 4 — Build your scanner

# Your first scanner should be dumb but useful.

# Signal 1: Large moves
# if abs(price_change_24h) > 0.10:
#     flag()

# Example:

# AI model release

# Yesterday:
# 35%

# Today:
# 52%

# Move:
# +17%
# Signal 2: Liquidity opportunities
# if spread > 0.08:
#     flag()
# Signal 3: Volume spikes
# if volume_today > 5 * average_volume:
#     flag()

# Your output:

# TOP MARKETS TO REVIEW

# 1.
# Question:
# Will Fed cut rates?

# Price:
# 42%

# 24h move:
# +12%

# Reason:
# Large movement


# 2.
# Question:
# Will Company X acquire Y?

# Price:
# 33%

# Spread:
# 11 cents

# Reason:
# Wide market
# Day 5 — Add your probability workflow

# Do NOT automate this yet.

# Create a manual table:

# trade_journal.csv

# market,current_price,my_probability,edge,reason
# Fed cut,0.42,0.55,0.13,"Inflation falling"
# AI launch,0.35,0.45,0.10,"Company comments"

# The key question:

# Market probability:
# 42%

# My probability:
# 55%

# Difference:
# +13%
# Day 6 — Paper trading

# Before your C++ engine touches anything:

# Create:

# paper_buy(
#     market,
#     price,
#     size
# )

# Track:

# Position:
# YES Fed cut

# Entry:
# 42c

# Size:
# $100

# Current:
# 48c

# P&L:
# +$14
# Day 7 — Analytics

# Calculate:

# Return
# profit / capital
# Drawdown

# Largest loss from peak.

# Sortino

# Track:

# returns
# negative returns only

# Your output:

# Paper Portfolio

# Trades:
# 18

# Win rate:
# 61%

# Return:
# +8.4%

# Max drawdown:
# -2.1%

# Sortino:
# 2.4